Home/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    #/Home/
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^$', views.logout_user, name='logout_user'),
    url(r'^welcome/$', views.welcome, name='welcome'),

]

datacenter/urls.py

from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include(('Home.urls','home'), namespace='home')),
    url(r'^music/', include('music.urls')),
    url(r'^video/', include('video.urls')),
    url(r'^image/', include('image.urls')),
    url(r'^table/', include('table.urls')),
    url(r'^document/', include(('document.urls', 'document'), namespace='document')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'image'


urlpatterns = [
    #/image/
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^create_folder/$', views.ImageFolderCreate.as_view(), name='create_folder'),
    url(r'^(?P<folder_id>[0-9]+)/create_image/$', views.create_image, name='create_image'),
    url(r'^(?P<folder_id>[0-9]+)/delete_folder/$', views.delete_folder, name='delete_folder'),
    url(r'^(?P<folder_id>[0-9]+)/delete_image/(?P<image_id>[0-9]+)/$', views.delete_image, name='delete_image'),
    url(r'^$', include('video.urls')),


 ]

music/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'music'


urlpatterns = [
    #/music/
    url(r'^$', views.index, name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    # /music/71/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /music/album/add/
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/2/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/2/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    url(r'^login/$', views.login_user, name='login_user'),

    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    url(r'^$', include('video.urls')),
]

table/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'table'


urlpatterns = [
    #/table/
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^create_table/$', views.TableCreate.as_view(), name='create_table'),
    url(r'^code/$', views.code, name='code'),
    url(r'^(?P<table_id>[0-9]+)/create_parameter/$', views.create_parameter, name='create_parameter'),
    #url(r'^(?P<table_id>[0-9]+)/create_parameter/$', views.ParameterCreate.as_view(), name='create_parameter'),
    url(r'^(?P<table_id>[0-9]+)/delete_table/$', views.delete_table, name='delete_table'),
    url(r'^$', include('video.urls')),


 ]

video/urls.py
from django.conf.urls import url
from . import views


app_name = 'video'


urlpatterns = [
    #/video/
    url(r'^$', views.index, name='index'),
    url(r'^create_folder/$', views.FolderCreate.as_view(), name='create_folder'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<folder_id>[0-9]+)/delete_folder/$', views.delete_folder, name='delete_folder'),
    url(r'^(?P<folder_id>[0-9]+)/create_video/$', views.create_video, name='create_video'),
    url(r'^(?P<folder_id>[0-9]+)/delete_video/(?P<video_id>[0-9]+)/$', views.delete_video, name='delete_video'),
    url(r'^back/$', views.home_return, name='home_return'),

 ]

Home/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render, redirect
from .form import UserForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.template.context_processors import csrf


def index(request):
    return render(request, 'home/index.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/home/welcome')
    context = {
        "form": form,
    }
    return render(request, 'home/register.html', context)


def login_user(request):
    c = {}
    c.update(csrf(request))
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'home/welcome.html')
            else:
                return render(request, 'home/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'home/login.html', {'error_message': 'Invalid login'})
    return render(request, 'home/login.html')


def welcome(request):
    return render(request, 'home/welcome.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'home/index.html', context)






Home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Home{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        html,body{
        background-image: url( "{% static 'home/wallpaper.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        height: 100%;
        color:white;
        }
    </style>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

Home/templates/home/index.html

{% extends 'home/base.html' %}
{% block title %}active{% endblock %}
{% block body %}
{% load static %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header ">
      <p class="navbar-brand navbar-right" ><a href="{%url 'home:index' %}">Welcome to AbdulRashid Datacenter</a></p>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="login_user"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <li><a href="register"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    </ul>
  </div>
</nav>

{% endblock %}

Home/templates/home/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">

</head>
<body>

<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input id="id_username" maxlength="30" name="username" type="text" placeholder="username">

					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input id="id_password" maxlength="30" name="password" type="password" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="{%url 'home:register' %}">Sign Up</a>
				</div>

			</div>
		</div>
	</div>
</div>

</body>

</html>

Home/templates/home/register.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Register{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
html,body{
    background-image: url( "{% static 'home/wallpaper.jpg' %}");
    background-size: cover;
    background-repeat: no-repeat;
    height: 100%;
    color:black;
    }

.container{
     align-content: center;
        	}

h3{
	align:center;
	}

.form-group{
    align:center;
}
</style>


</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header ">
      <p class="navbar-brand navbar-right" ><a href="{%url 'home:index' %}">Welcome to AbdulRashid Datacenter</a></p>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'home:register'%}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'home:login_user'%}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>

<div class="container">

    <div class="row">
        <div class="col-sm-12 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <legend>Personal information:</legend>
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

</body>

</html>

Home/templates/home/welcome.html
{% extends 'home/base.html' %}
{% block title %}Welcome{% endblock %}

{% block body %}
{% csrf_token %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header ">
      <p class="navbar-brand navbar-right" >Welcome to AbdulRashid Datacenter</p>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'document:index' %}"><span class="glyphicon glyphicon-file"></span>Documents</a></li>
      <li><a href="{% url 'video:index' %}"><span class="glyphicon glyphicon-facetime-video"></span> videos</a></li>
      <li><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-music"></span> Music</a></li>
      <li><a href="{% url 'table:index' %}"><span class="glyphicon glyphicon-menu-hamburger"></span> Tables</a></li>
      <li><a href="{% url 'image:index' %}"><span class="glyphicon glyphicon-picture"></span> Images</a></li>
      <li><a href="{% url 'home:logout_user' %}"><span class="glyphicon glyphicon-off"></span> Logout</a></li>
      <li><a href=""><span class="glyphicon glyphicon"></span>Welcome {{user}}</a></li>
    </ul>

  </div>
</nav>
{% endblock %}