Home/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    #/Home/
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^$', views.logout_user, name='logout_user'),
    url(r'^welcome/$', views.welcome, name='welcome'),

]

datacenter/urls.py

from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include(('Home.urls','home'), namespace='home')),
    url(r'^music/', include('music.urls')),
    url(r'^video/', include('video.urls')),
    url(r'^image/', include('image.urls')),
    url(r'^table/', include('table.urls')),
    url(r'^document/', include(('document.urls', 'document'), namespace='document')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'music'


urlpatterns = [
    #/music/
    url(r'^$', views.index, name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    # /music/71/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /music/album/add/
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/2/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/2/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    url(r'^login/$', views.login_user, name='login_user'),

    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    url(r'^$', include('video.urls')),
]

video/urls.py
from django.conf.urls import url
from . import views


app_name = 'video'


urlpatterns = [
    #/video/
    url(r'^$', views.index, name='index'),
    url(r'^create_folder/$', views.FolderCreate.as_view(), name='create_folder'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<folder_id>[0-9]+)/delete_folder/$', views.delete_folder, name='delete_folder'),
    url(r'^(?P<folder_id>[0-9]+)/create_video/$', views.create_video, name='create_video'),
    url(r'^(?P<folder_id>[0-9]+)/delete_video/(?P<video_id>[0-9]+)/$', views.delete_video, name='delete_video'),
    url(r'^back/$', views.home_return, name='home_return'),

 ]

video/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Folder(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, default=1, on_delete=models.CASCADE)
    folder_title = models.CharField(blank=True, null=True, max_length=500)

    folder_logo = models.FileField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('video:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.folder_title


class Video(models.Model):
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    video_title = models.CharField(max_length=250)
    video_file = models.FileField(default='')

    def __str__(self):
        return self.video_title

video/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Folder, Video


class FolderForm(forms.ModelForm):

    class Meta:
        model = Folder
        fields = ['folder_title', 'folder_logo']


class VideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ['video_title', 'video_file']



video/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .forms import  VideoForm
from Home.form import UserForm
from django.views import generic
from django.db.models import Q
from .models import Folder, Video
from django.views.generic.edit import CreateView

from django.contrib.auth.models import User

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
VIDEO_FILE_TYPES = ['ts', 'mp4', 'mkv']


class DetailView(generic.DetailView):
    model = Folder
    template_name = 'video/detail.html'


class FolderCreate(CreateView):
    model = Folder
    fields = ['folder_title', 'folder_logo']

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(FolderCreate, self).form_valid(form)

def delete_folder(request, folder_id):
    folder = Folder.objects.get(pk=folder_id)
    folder.delete()
    folder = Folder.objects.filter(user=request.user)
    return redirect('/video')


def index(request):
    if not request.user.is_authenticated:
        return render(request, 'home/login.html')
    else:
        folder = Folder.objects.filter(user=request.user)
        video_results = Video.objects.all()
        query = request.GET.get("q")
        if query:
            folder = folder.filter(
                Q(folder_title__icontains=query)

            ).distinct()
            video_results = video_results.filter(
                Q(video_title__icontains=query)
            ).distinct()
            return render(request, 'video/index.html', {
                'folder': folder,
                'video': video_results,
            })
        else:
            return render(request, 'video/index.html', {'folder': folder})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return redirect('/home')


def create_video(request, folder_id):
    form = VideoForm(request.POST or None, request.FILES or None)
    folder = get_object_or_404(Folder, pk=folder_id)
    if form.is_valid():
        folder_video = folder.video_set.all()
        for s in folder_video:
            if s.video_title == form.cleaned_data.get("video_title"):
                context = {
                    'folder': folder,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'video/create_video.html', context)
        video = form.save(commit=False)
        video.folder = folder
        video.video_file = request.FILES['video_file']
        file_type = video.video_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in VIDEO_FILE_TYPES:
            context = {
                'folder': folder,
                'form': form,
                'error_message': 'Video file must be TS, MP4, or MKV',
            }
            return render(request, 'video/create_video.html', context)

        video.save()
        return render(request, 'video/detail.html', {'folder': folder})
    context = {
        'folder': folder,
        'form': form,
    }
    return render(request, 'video/create_video.html', context)


def delete_video(request, folder_id, video_id):
    folder = get_object_or_404(Folder, pk=folder_id)
    video = Video.objects.get(pk=video_id)
    video.delete()
    return render(request, 'video/detail.html', {'folder': folder})


def home_return(request):
    return render(request, 'home/welcome.html')




video/templates/video/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Image{% endblock %}</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<style>
          html,body{ background-image: url( "{% static 'image/wallpaper.jpg' %}");
background-size: cover;
background-repeat: no-repeat;
height: 100%;
 }
</style>
<body>
{% block body %}
{% endblock %}
</body>
</html>

video/templates/video/create_video.html
{% extends 'video/base.html' %}
{% block title %}Add a New Video{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'video:detail' folder.id %}">
                            {% if folder.folder_logo %}
                                <img src="{{ folder.folder_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ folder.folder_title }}</h1>

                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'video:detail' folder.id %}">View All</a></li>

            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New video</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="folder" value="{{ folder }}">
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

video/templates/video/detail.html
{% extends 'video/base.html' %}
{% block title %}{{ folder }}{% endblock %}

{% block body %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#" style="font-family: 'Satisfy', cursive;border-radius: 0;">Welcome to AbdulRashid Datacenter</a>
        </div>
        <!--items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'video:index' %}">
                        <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp;
                        Folders
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'video:home_return' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                        Home
                    </a>
                 </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'video:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="" >
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                    <a href="{% url 'video:create_folder' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Create Folder
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'video:logout_user'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Folder Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'video:detail' folder.id %}">
                        {% if folder.folder_logo %}
                            <img src="{{ folder.folder_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ folder.folder_title }} </h1>

                </div>
            </div>
        </div>

        <!-- Right Video Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'video:detail' folder.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'video:create_video' folder.id %}">Add New video</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All video</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Video File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for video in folder.video_set.all %}
                            <tr>
                                <td>{{ video.video_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ video.video_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if video.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'video:delete_video' folder.id video.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="video_id" value="{{ video.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>



{% endblock %}

video/templates/video/folder.html
{% extends 'video/base.html' %}


{% block body %}
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#" style="font-family: 'Satisfy', cursive;border-radius: 0;">Welcome to AbdulRashid Datacenter</a>
        </div>
        <!--items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'video:folder' %}">
                        <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp;
                        Folders
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="" >
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                    <a href="{% url 'video:create_folder' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Create Folder
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'video:logout_user'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Folder</h3>
        </div>
        {% if object_list %}
            {% for folder in object_list %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="#">
                            <img src="{{ folder.folder_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ folder.folder_title }}</h2>


                            <!-- View Details -->
                            <a href="#" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="#" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'video:create_folder' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Create Folder
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs-->
    {% if video %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Videos</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Video Title</th>

                                    <th>Video File</th>
                                    <th>Folder</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for video in video %}
                                    <tr>
                                        <td>{{ video.video_title }}</td>

                                        <td>
                                            <a target="_blank" href="{{ video.video_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'video:folder' video.folder.id %}">
                                                <img src="{{ video.folder.folder_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'video:folder' video.folder.id %}">{{ video.folder.folder_title }}</a>
                                        </td>

                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

video/templates/video/form_template.html
{% for field in form %}
   <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="image_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

video/templates/video/index.html
{% extends 'video/base.html' %}
{% block albums_active %}video{% endblock %}

{% block body %}
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#" style="font-family: 'Satisfy', cursive;border-radius: 0;">Welcome to AbdulRashid Datacenter</a>
        </div>
        <!--items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'video:index' %}">
                        <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp;
                        Folders
                    </a>
                    <li class="">
                    <a href="{% url 'video:home_return' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                        Home
                    </a>
                 </li>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'video:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="" >
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                    <a href="{% url 'video:create_folder' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Create Folder
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'video:logout_user'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="albums-container container-fluid">

    <!-- Folder -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Folder</h3>
        </div>
        {% if folder %}
            {% for folder in folder %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'video:detail' folder.id %}">
                            {% if folder.folder_logo %}
                            <img src="{{ videofolder.folder_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}

                        </a>

                        <div class="caption">
                            <h2>{{ folder.folder_title }}</h2>


                            <!-- View Details -->
                            <a href="{% url 'video:detail' folder.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'video:delete_folder' folder.id%}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="folder_id" value="{{ folder.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->


                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'video:create_folder' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Folder
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if video %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Videos</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Video Title</th>

                                    <th>Video File</th>
                                    <th>Folder</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for folder in folder %}
                                    <tr>
                                        <td>{{ video.video_title }}</td>

                                        <td>
                                            <a target="_blank" href="{{ video.video_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'video:detail' video.folder.id %}">
                                                <img src="{{ video.folder.folder_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'video:detail' video.folder.id %}">{{ video.folder.folder_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'video:favorite' video.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if video.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}