Home/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    #/Home/
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^$', views.logout_user, name='logout_user'),
    url(r'^welcome/$', views.welcome, name='welcome'),

]

datacenter/urls.py

from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include(('Home.urls','home'), namespace='home')),
    url(r'^music/', include('music.urls')),
    url(r'^video/', include('video.urls')),
    url(r'^image/', include('image.urls')),
    url(r'^table/', include('table.urls')),
    url(r'^document/', include(('document.urls', 'document'), namespace='document')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

document/urls.py
from django.conf.urls import url
from . import views

app_name = 'document'


urlpatterns = [
    #/document/
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^create_folder/$', views.DocumentFolderCreate.as_view(), name='create_folder'),
    url(r'^(?P<folder_id>[0-9]+)/create_document/$', views.create_document, name='create_document'),
    url(r'^(?P<folder_id>[0-9]+)/delete_folder/$', views.delete_folder, name='delete_folder'),
    url(r'^(?P<folder_id>[0-9]+)/delete_document/(?P<document_id>[0-9]+)/$', views.delete_document, name='delete_document'),
]

image/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'image'


urlpatterns = [
    #/image/
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^create_folder/$', views.ImageFolderCreate.as_view(), name='create_folder'),
    url(r'^(?P<folder_id>[0-9]+)/create_image/$', views.create_image, name='create_image'),
    url(r'^(?P<folder_id>[0-9]+)/delete_folder/$', views.delete_folder, name='delete_folder'),
    url(r'^(?P<folder_id>[0-9]+)/delete_image/(?P<image_id>[0-9]+)/$', views.delete_image, name='delete_image'),
    url(r'^$', include('video.urls')),


 ]

video/urls.py
from django.conf.urls import url
from . import views


app_name = 'video'


urlpatterns = [
    #/video/
    url(r'^$', views.index, name='index'),
    url(r'^create_folder/$', views.FolderCreate.as_view(), name='create_folder'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<folder_id>[0-9]+)/delete_folder/$', views.delete_folder, name='delete_folder'),
    url(r'^(?P<folder_id>[0-9]+)/create_video/$', views.create_video, name='create_video'),
    url(r'^(?P<folder_id>[0-9]+)/delete_video/(?P<video_id>[0-9]+)/$', views.delete_video, name='delete_video'),
    url(r'^back/$', views.home_return, name='home_return'),

 ]

document/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class DocumentFolder(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, default=1, on_delete=models.CASCADE)
    folder_title = models.CharField(blank=True, null=True, max_length=500)

    folder_logo = models.FileField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('document:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.folder_title


class Document(models.Model):
    folder = models.ForeignKey(DocumentFolder, on_delete=models.CASCADE)
    document_title = models.CharField(max_length=250)
    document_file = models.FileField(default='')

    def __str__(self):
        return self.document_title

document/forms.py
from django import forms
from .models import Document


class DocumentForm(forms.ModelForm):

    class Meta:
        model = Document
        fields = ['document_title', 'document_file']

document/views.py
from .models import DocumentFolder,Document
from django.views.generic.edit import CreateView
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect
from .forms import DocumentForm
from django.db.models import Q

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'home/login.html')
    else:
        folder = DocumentFolder.objects.filter(user=request.user)
        image_results = Document.objects.all()
        query = request.GET.get("q")
        if query:
            folder = folder.filter(
                Q(folder_title__icontains=query)

            ).distinct()
            document_results = image_results.filter(
                Q(document_title__icontains=query)
            ).distinct()
            return render(request, 'document/index.html', {
                'folder': folder,
                'document': document_results,
            })
        else:
            return render(request, 'document/index.html', {'folder': folder})


class DocumentFolderCreate(CreateView):
    model = DocumentFolder
    fields = ['folder_title', 'folder_logo']

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(DocumentFolderCreate, self).form_valid(form)


class DetailView(generic.DetailView):
    model = DocumentFolder
    template_name = 'document/detail.html'


def create_document(request, folder_id):
    form = DocumentForm(request.POST or None, request.FILES or None)
    documentfolder = get_object_or_404(DocumentFolder, pk=folder_id)
    if form.is_valid():
        folder_doc = documentfolder.document_set.all()
        for s in folder_doc:
            if s.document_title == form.cleaned_data.get("document_title"):
                context = {
                    'folder': documentfolder,
                    'form': form,
                    'error_message': 'You already added that document',
                }
                return render(request, 'document/create_document.html', context)
        document = form.save(commit=False)
        document.folder = documentfolder
        document.document_file = request.FILES['document_file']
        document.save()
        return render(request, 'document/detail.html', {'documentfolder': documentfolder})
    context = {
        'folder': documentfolder,
        'form': form,
    }
    return render(request, 'document/create_document.html', context)


def delete_folder(request, folder_id):
    folder = DocumentFolder.objects.get(pk=folder_id)
    folder.delete()
    folder = DocumentFolder.objects.filter(user=request.user)
    return redirect('/document')


def delete_document(request, folder_id, document_id):
    documentfolder = get_object_or_404(DocumentFolder, pk=folder_id)
    document = Document.objects.get(pk=document_id)
    document.delete()
    return render(request, 'document/detail.html', {'documentfolder': documentfolder})




document/templates/document/create_document.html
{% extends 'image/base.html' %}
{% block title %}Add a New Document{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'document:detail' folder.id %}">
                            {% if folder.folder_logo %}
                                <img src="{{ folder.folder_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ folder.folder_title }}</h1>

                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Document</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="folder" value="{{ folder }}">
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

document/templates/document/detail.html
{% extends 'image/base.html' %}
{% block title %}{{ documentfolder }}{% endblock %}

{% block body %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#" style="font-family: 'Satisfy', cursive;border-radius: 0;">Welcome to AbdulRashid Datacenter</a>
        </div>
        <!--items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'document:index' %}">
                        <span class="glyphicon glyphicon-folders" aria-hidden="true"></span>&nbsp;
                        Folders
                    </a>
                    <li class="">
                    <a href="{% url 'video:home_return' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                        Home
                    </a>
                 </li>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="" >
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                    <a href="{% url 'document:create_folder' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Create Folder
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'video:logout_user'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Folder Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'document:detail' documentfolder.id %}">
                        {% if documentfolder.folder_logo %}
                            <img src="{{ documentfolder.folder_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ Documentfolder.folder_title }} </h1>

                </div>
            </div>
        </div>

        <!-- Right Video Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'document:detail' documentfolder.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'document:create_document' documentfolder.id %}">Add New Document</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All documents</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>document File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for document in documentfolder.document_set.all %}
                            <tr>
                                <td>{{ document.document_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ document.document_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Show
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if document.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'document:delete_document' documentfolder.id document.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="doc_id" value="{{ document.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

document/templates/document/documentfolder_form.html
{% extends 'image/base.html' %}
{% block body %}
<div class="container-fluid">
   <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'document/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
   </div>
</div>
{% endblock %}

document/templates/document/form_template.html
{% for field in form %}
   <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="document_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}


document/templates/document/index.html
{% extends 'image/base.html' %}
{% block title %}Document{% endblock %}
{% block albums_active %}video{% endblock %}

{% block body %}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#" style="font-family: 'Satisfy', cursive;border-radius: 0;">Welcome to AbdulRashid Datacenter</a>
        </div>
        <!--items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'document:index' %}">
                        <span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span>&nbsp;
                        Folders
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'video:home_return' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                        Home
                    </a>
                 </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="" >
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                    <a href="{% url 'document:create_folder' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Create Folder
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'video:logout_user'%}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="albums-container container-fluid">

    <!-- Folder -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Folder</h3>
        </div>
        {% if folder %}

            {% for folder in folder %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'image:detail' folder.id %}">
                            {% if folder.folder_logo %}
                            <img src="{{ documentfolder.folder_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}

                        </a>
                        <div class="caption">
                            <h2>{{ folder.folder_title }}</h2>


                            <!-- View Details -->
                            <a href="{% url 'document:detail' folder.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'document:delete_folder' folder.id%}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="folder_id" value="{{ folder.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->


                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'document:create_folder' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Folder
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are images -->
    {% if document %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Documents</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Document Title</th>

                                    <th>Document File</th>
                                    <th>Folder</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for documentfolder in folder %}
                                    <tr>
                                        <td>{{ document.image_title }}</td>

                                        <td>
                                            <a target="_blank" href="#">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="#">
                                                <img src="#" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="#">{{ document.folder.folder_title }}</a>
                                        </td>
                                        <td>
                                            <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if document.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>

{% endblock %}